config/routes.rb
Rails.application.routes.draw do

  # defined the root path, witch will be managed by main controller action index
  root to: 'main#index'
  
  # about page route
  get 'about', to: 'about#index'
  
  # password update routes
  get 'password', to: 'passwords#edit', as: :edit_password # We are telling rails that we want to set the path helper as edit_password_pass
  patch 'password', to: 'passwords#update'

  # password reset route
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  

  # sign_up routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'  

  #sign_in routes
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  # log_out route
  delete 'logout', to: 'sessions#destroy'

  # omniauth twitter routes
  get 'auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_now # 'deliver_later' causes email to be sent in background job.
                                                         # the other option is 'deliver_now'
    end
    redirect_to root_path, notice: 'We have sent a link to reset your password'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: 'Your token has expired. Please, try again'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to sign_in_path, notice: 'Your password was reset successfully. Please, log in'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end



end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
  <%= render 'shared/form_errors', f: f %>  
  <div class="form-group mb-2">
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password,class: 'form-control', placeholder: 'Password' %>
  </div>
  <div class="form-group mb-2">
    <%= f.label :password_confirmation, 'Password confirmation' %>
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password confirmation' %>
  </div>
  <div>
    <%= f.submit 'Reset Password', class: 'btn btn-primary mt-2', disable_with: 'Submiting...' %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |f| %>
  <div class="form-group mb-2">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, class: 'form-control', placeholder: 'steve@email.com' %>    
  </div>
  <div>
    <%= f.submit 'Reset Password', class: 'btn btn-primary mt-2', disable_with: 'Submiting...' %>
  </div>
<% end %>