config/routes.rb
Rails.application.routes.draw do

  # defined the root path, witch will be managed by main controller action index
  root to: 'main#index'
  
  # about page route
  get 'about', to: 'about#index'
  
  # password update routes
  get 'password', to: 'passwords#edit', as: :edit_password # We are telling rails that we want to set the path helper as edit_password_pass
  patch 'password', to: 'passwords#update'

  # password reset route
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  

  # sign_up routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'  

  #sign_in routes
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  # log_out route
  delete 'logout', to: 'sessions#destroy'

  # omniauth twitter routes
  get 'auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 48.hour.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id? # Rails provides this kind of sintax to refer to a column name in our database. table: tweets -->   tweet_id 
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:edit, :update, :show, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.create(tweet_params)
    if @tweet.save
      # Here we are calling a background job called Tweet, which will publish the tweet on the date set in the 'publish_at' column
      redirect_to tweets_path, notice: 'Tweet was scheduled successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update    
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Tweet was updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: 'Tweet was unscheduled'
    
  end

  private
    def tweet_params
      params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
    end

    def set_tweet
      @tweet = Current.user.tweets.find(params[:id])
    end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet, data: { turbo: false } do |f| %>
 <%= render '/shared/form_errors', f: f %>
  <div class="mb-3">
    <%= f.label :twitter_account_id %>
    <%= f.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: 'form-control' } %>
    <%= link_to 'Connect your Twitter Account', '/auth/twitter' %>
  </div>
  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>    
  </div>

  <div class="mb-3">
    <%= f.label :publish_at %>
    <div class="form-control">
      <%= f.datetime_select :publish_at %>
    </div>
  </div>

  <%= f.button 'Schedule', class: 'btn btn-primary'%>

  <!-- with this condition, f.object <the object being handled by the form> .persisted? 
       we are displaying a 'Delete' button if there is any object in the form (the form is not empty) -->
  <% if f.object.persisted? %>
    <%= button_to 'Delete', f.object, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
  <% end %>  
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>
  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class: 'rounded-circle' %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>

    <% if tweet.published? %>
      <%= link_to 'View Tweet', "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
      Scheduled for <%= l tweet.publish_at, format: :short %> <!-- take a look at the Rails localize helper 'l' that recives 2 parameters
                                                                   the date, and the format we want, and automaticly convert the date into our fotmat-->
      <%= link_to 'Edit Tweet', edit_tweet_path(tweet) %>                                                                   
    <% end %>      
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render 'form', tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= link_to 'Schedule a Tweet', new_tweet_path, class: 'btn btn-primary' %>
  <% end %>

  <% if Current.user.twitter_accounts.none? %>
    <%= button_to 'Connect your Twitter Account', '/auth/twitter', class: 'btn btn-primary', method: :post, data: { turbo: false } %>
  <% end %>
  
</div>
  <%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= render 'form', tweet: @tweet %>