config/routes.rb
Rails.application.routes.draw do

  # defined the root path, witch will be managed by main controller action index
  root to: 'main#index'
  
  # about page route
  get 'about', to: 'about#index'
  
  # password update routes
  get 'password', to: 'passwords#edit', as: :edit_password # We are telling rails that we want to set the path helper as edit_password_pass
  patch 'password', to: 'passwords#update'

  # password reset route
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  

  # sign_up routes
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'  

  #sign_in routes
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  # log_out route
  delete 'logout', to: 'sessions#destroy'

  # omniauth twitter routes
  get 'auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %> 
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if f.object.errors.any? %>
  <div class="alert alert-danger">
    <% f.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>      
    <% end %>      
  </div>
<% end %> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Twitter Accounts', twitter_accounts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tweets', tweets_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <!-- In previous versions of RoR (< 6), we can change the method of the links requets through javascript -->
            <!-- Now, with HOTWIRE, is better choice using button_to with method: :delete -->
            <%= button_to 'log out', logout_path, method: :delete, class: 'nav-link btn btn-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', sign_up_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>